apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if eq .Values.ingress.access_policy "public" }}
    ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  {{- end }}
  {{- if .Values.ingress.ssl }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  {{- if .Values.ingress.ssl }}
  tls:
    - hosts:
      - {{ .Values.ingress.name }}.{{ .Values.cluster }}.{{ .Values.ingress.subdomain }}.mnscorp.net
      - {{ .Values.ingress.name }}.pre-live.{{ .Values.cluster }}.{{ .Values.ingress.subdomain }}.mnscorp.net
      secretName: {{ template "name" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.name }}.{{ .Values.cluster }}.{{ .Values.ingress.subdomain }}.mnscorp.net
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: http
    - host: {{ .Values.ingress.name }}.pre-live.{{ .Values.cluster }}.{{ .Values.ingress.subdomain }}.mnscorp.net
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "fullname" . }}
servicePort: http
