# cluster: dev
namespace: api-digitalservices-dev

dockerImage: registry.opensource.zalan.do/tip/docker-locust
dockerTag: latest
dockerPort: 8089
args: -i --rm -v $PWD/reports:/opt/reports -v ~/.aws:/root/.aws -v $PWD/:/opt/script -v $PWD/credentials:/meta/credentials -p 8089:8089 -e ROLE=standalone -e TARGET_HOST=https://content-v2.perf.apis.devops.mnscorp.net -e LOCUST_FILE=https://raw.githubusercontent.com/neerajagr/testRepo/master/simple.py -e SLAVE_MUL=4 -e AUTOMATIC=False registry.opensource.zalan.do/tip/docker-locust

# Container environment variables
ENV:
 ROLE: standalone
 TARGET_HOST: "https://content-v2.perf.apis.devops.mnscorp.net"
 LOCUST_FILE: "https://raw.githubusercontent.com/neerajagr/testRepo/master/simple.py" 
 SLAVE_MUL: 4
 AUTOMATIC: False

# Profile
profile: dev  -Xms512m -Xmx2048m

# For production always higher than 1, because if one pod dies your app will be unavailable until the pod recovers.
replicas: 2
replicasMax: 4

# Limits
cpuTargetPercentage: 50

ingress:
  name: mnslocust
  subdomain: apps

  # Mark ssl as true to enable SSL on this service
  ssl: false

  access_policy: public

  # Mark metric as true to enable custom metrics for your application
  metric: true

resources:
  requests:
    memory: 100Mi
cpu: 200m
